testing full deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,18 +6,74 @@ on:
       - cloudrun
 
 jobs:
-  deploy:
+  database:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4.1.7
 
-    # - name: Set up Java 17
-    #   uses: actions/setup-java@v4
-    #   with:
-    #     distribution: 'temurin'
-    #     java-version: '17'
+    - name: Copy docker-compose.yml to VM
+      uses: garygrossgarten/github-action-scp@release
+      with:
+        host: ${{ secrets.VM_HOST }}
+        local: 'docker-compose.yml'
+        username: ${{ secrets.VM_USER }}
+        remote: '/home/${{ secrets.VM_USER }}/linkedout/docker-compose.yml'
+        privateKey: ${{ secrets.SSH_PRIVATE }}
+
+    - name: Deploying Postgres database container
+      uses: appleboy/ssh-action@v1.0.3
+      with:
+        host: ${{ secrets.VM_HOST }}
+        username: ${{ secrets.VM_USER }}
+        key: ${{ secrets.SSH_PRIVATE }}
+        script: |
+          cd ~/linkedout
+          sudo docker compose -f docker-compose.yml down
+          sudo docker compose -f docker-compose.yml up -d
+
+  wait-cloud-build:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Auth with Google Cloud
+      uses: 'google-github-actions/auth@v2'
+      with:
+        project_id: tinypet-404519
+        credentials_json: ${{ secrets.GCP_SA_KEY }}
+        service_account: 'owner-318@tinypet-404519.iam.gserviceaccount.com'
+
+    - name: Setup Google Cloud SDK
+      uses: google-github-actions/setup-gcloud@v2
+      with:
+        project_id: tinypet-404519
+
+    - name: Wait for Cloud Build to finish
+      run: |
+        TRIGGER_ID="YOUR_TRIGGER_ID"
+        PROJECT_ID="tinypet-404519"
+        echo "Polling for Cloud Build trigger completion..."
+        while :
+        do
+          STATUS=$(gcloud builds list --project=${PROJECT_ID} --format="value(status)" --limit=1)
+          echo "Current status: $STATUS"
+          if [ "$STATUS" == "SUCCESS" ]; then
+            echo "Cloud Build completed successfully."
+            break
+          elif [ "$STATUS" == "FAILURE" ] || [ "$STATUS" == "CANCELLED" ]; then
+            echo "Cloud Build failed or was cancelled."
+            exit 1
+          fi
+          sleep 50
+        done
+
+  deploy-frontend:
+    runs-on: ubuntu-latest
+    needs: wait-cloud-build
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4.1.7
 
     - name: Set up Node.js
       uses: actions/setup-node@v4
@@ -27,50 +83,34 @@ jobs:
     - id: 'auth'
       uses: 'google-github-actions/auth@v2'
       with:
-        project_id: ${{ secrets.GCP_PROJECT_ID }}
+        project_id: tinypet-404519
         credentials_json: ${{ secrets.GCP_SA_KEY }}
         service_account: 'owner-318@tinypet-404519.iam.gserviceaccount.com'
 
     - name: Setup Google Cloud SDK
       uses: google-github-actions/setup-gcloud@v2
       with:
-        project_id: ${{ secrets.GCP_PROJECT_ID }}
+        project_id: tinypet-404519
 
-    # - name: Perform the build and deploy to Cloud Run
-    #   run: |
-    #     gcloud builds submit --config backend/cloudbuild.yaml backend
+    - name: Get Cloud Run URL
+      id: get-url
+      run: |
+        URL=$(gcloud run services describe linkedout --region=europe-west1 --format='json(metadata.annotations."run.googleapis.com/urls")[0]')
+        URL=$(echo $URL | jq -r '.metadata.annotations."run.googleapis.com/urls" | fromjson[0]')
+        echo "URL=$URL" >> $GITHUB_ENV
       
-    # - name: Install frontend dependencies
-    #   run: |
-    #     cd frontend
-    #     npm install -g @angular/cli
-    #     npm install -g angular-cli-ghpages
-    #     npm install
+    - name: Install frontend dependencies
+      run: |
+        cd frontend
+        echo "export const environment = { production: true, hostUrl: '${{ env.URL }}' };" > src/environments/environment.ts
+        npm install -g @angular/cli
+        npm install -g angular-cli-ghpages
+        npm install
 
-    # - name: Copy docker-compose.yml to VM
-    #   uses: garygrossgarten/github-action-scp@release
-    #   with:
-    #     host: ${{ secrets.VM_HOST }}
-    #     local: 'docker-compose.yml'
-    #     username: ${{ secrets.VM_USER }}
-    #     remote: '/home/${{ secrets.VM_USER }}/linkedout/docker-compose.yml'
-    #     privateKey: ${{ secrets.SSH_PRIVATE }}
-
-    # - name: Deploying Postgres database container
-    #   uses: appleboy/ssh-action@v1.0.3
-    #   with:
-    #     host: ${{ secrets.VM_HOST }}
-    #     username: ${{ secrets.VM_USER }}
-    #     key: ${{ secrets.SSH_PRIVATE }}
-    #     script: |
-    #       cd ~/linkedout
-    #       sudo docker compose -f docker-compose.yml down
-    #       sudo docker compose -f docker-compose.yml up -d
-
-    # - name: Build and deploy the frontend
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-    #   run: |
-    #     cd frontend
-    #     ng build --base-href /LinkedOut/ --configuration production
-    #     ngh --dir=dist/browser --no-silent
+    - name: Build and deploy the frontend
+      env:
+        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+      run: |
+        cd frontend
+        ng build --base-href /LinkedOut/ --configuration production
+        ngh --dir=dist/browser --no-silent
